### ISSUE TITLE
Upload and comparison of calibrate URDF panda with franka_description

### ISSUE THREAD

**Issue by franzesegiovanni** [PhilNad/robot-arm-kinematic-calibration#1]
Dear PhilNad, 

Thank you for this repo. I came across this in the franka community when trying to figure out why my panda moves 1 cm to the side while changing joint configuration, the controller believes that the Cartesian error is only 1 mm. I wondered if the kinematics should be miscalibrated. 

I would like to ask you if you have run your calibration on a Panda or an FR3 and if you already have the resulting URDF. Which are the parameters that are actually off? It would be of great help if you could share your results. You may also create a repo called franka_description_calibrated. It would be very useful. I would link my controllers to that and test that it works better. 
Have you tried to run the calibration on different robots? Does it always end up with the same urdf parameters ?

Thank you in advance. I am looking forward to your reply. 

Kind Regards, 

Giovanni

**Comment by PhilNad** [comment]
Hi Giovanni,

It is very likely that the accuracy problems you are experiencing are due to kinematic calibration errors. Although my tests were performed on a FR3, the Panda has the same kinematic structure as the FR3 according to Franka's documentation (only joint limits and velocity limits are different).

The kinematic parameters I get after the calibration are listed [here](https://github.com/PhilNad/robot-arm-kinematic-calibration#real-robot-example) and you can compare them to the nominal ones [here](https://github.com/frankaemika/franka_description/blob/main/robots/fr3/kinematics.yaml). You will see that there is quite a difference.

Since the calibration must be done on a per-robot basis, I don't think that it would be very useful to dedicate a repository to the results I have with my particular robot. I have a second FR3 I could calibrate to see the difference and have an idea on the variance of the offsets (although with only two sample points). I will certainly get different parameters with the second robot.

Hopefully that answers your questions.

Cheers,
Philippe

**Comment by PhilNad** [comment]
Closing the issue as the question seems to be answered.
